site_name: My Docs
site_url: https://KumarRajan1.io/New_MkDocs/

theme:
  name: material
  custom_dir: docs
  features:
    - navigation.instant
  palette:
    scheme: default
  extra_css:
    - styles/custom.css

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
