site_name: Mappls Docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: img/logo.svg

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - styles/custom.css

extra_javascript:
  - js/disable-instant-on-swagger.js
 
  