name: Deploy and Trigger Docs Build

on:
  push:
    branches:
      - main  # Or the branch you want to trigger from

permissions:
  contents: write  # Required for deploying to gh-pages

jobs:
  deploy:
    name: Deploy MkDocs Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site

  trigger:
    name: Trigger Docs in New_MkDocs
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger New_MkDocs Repo Build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: KumarRajan1/New_MkDocs
          event-type: build_docs
